services:
    contao.frontend.controller.posts:
        class: Agoat\PostsnPagesBundle\Frontend\PostController
        public: false
        tags:
            - { name: permalink.controller, context: post }

    contao.picker.post_provider:
        class: Agoat\PostsnPagesBundle\Picker\PostPickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider, priority: 128 }
            
    contao.picker.archive_provider:
        class: Agoat\PostsnPagesBundle\Picker\ArchivePickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider, priority: 64 }
            
    contao.picker.static_provider:
        class: Agoat\PostsnPagesBundle\Picker\StaticPickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider, priority: 32 }
            
    contao.picker.article_provider:
        abstract: true
