services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Contao\CoreBundle\Framework\ContaoFramework: "@contao.framework"

    Agoat\PostsnPagesBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,ContaoManager}'

    contao.picker.post_provider:
        class: Agoat\PostsnPagesBundle\Picker\PostPickerProvider
        public: false
        tags:
            - { name: contao.picker_provider, priority: 128 }

    contao.picker.archive_provider:
        class: Agoat\PostsnPagesBundle\Picker\ArchivePickerProvider
        public: false
        tags:
            - { name: contao.picker_provider, priority: 64 }

    contao.picker.static_provider:
        class: Agoat\PostsnPagesBundle\Picker\StaticPickerProvider
        public: false
        tags:
            - { name: contao.picker_provider, priority: 32 }

    contao.picker.article_provider:
        abstract: true


    Agoat\PostsnPagesBundle\Permalink\PostPermalinkHandler:
        public: false
        bind:
            $requestStack: "@request_stack"
            $suffix: "%contao.url_suffix%"
        tags: [ 'permalink.handler' ]

#    contao.listener.add_posts_to_search_index:
#        class: Agoat\PostsnPagesBundle\EventListener\AddToSearchIndexListener
#        arguments:
#            - "@contao.framework"
#            - "%fragment.path%"
#        tags:
#            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.post_preview_url_create:
        class: Agoat\PostsnPagesBundle\EventListener\PostPreviewUrlCreateListener
        arguments:
            - "@request_stack"
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_create, method: onPreviewUrlCreate }

    contao.listener.page_preview_url_create:
        class: Agoat\PostsnPagesBundle\EventListener\PagePreviewUrlCreateListener
        arguments:
            - "@request_stack"
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_create, method: onPreviewUrlCreate }

    contao.listener.post_preview_url_convert:
        class: Agoat\PostsnPagesBundle\EventListener\PostPreviewUrlConvertListener
        arguments:
            - "@request_stack"
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_convert, method: onPreviewUrlConvert }

    contao.relation.provider.container:
        class: Agoat\PostsnPagesBundle\LanguageRelation\ContainerLanguageRelationProvider
        tags:
            - { name: contao.languagerelation_provider }

    contao.relation.provider.archive:
        class: Agoat\PostsnPagesBundle\LanguageRelation\ArchiveLanguageRelationProvider
        tags:
            - { name: contao.languagerelation_provider }

    contao.relation.provider.post:
        class: Agoat\PostsnPagesBundle\LanguageRelation\PostLanguageRelationProvider
        tags:
            - { name: contao.languagerelation_provider }
